using PnzApi.Authentication;
using PnzApi.Core;
using PnzApi.Core.Authentication;
using PnzApi.Core.ErrorResponse;
using PnzApi.Core.Response;
using PnzApi.Core.Request;
using PnzApi.Core.Models;
using PnzApi.Models;

namespace PnzApi;

public class PnzApiClient
{
    private readonly RawClient _rawClient;

    private readonly IAuthScheme _httpBearerScheme;

    public PnzApiClient(HttpClient httpClient, PnzApiClientOptions options, string? token = null)
    {
        const string baseUrl = "https://api-nomatls.apicentre.middleware.co.nz/open-banking-nz/v2.3";
        var queryParameterFactory = new QueryParameterFactory([]);
        var templateParamsFactory = new TemplateParamsFactory([]);
        var urlFactory = new UriFactory(baseUrl, queryParameterFactory, templateParamsFactory);
        var responseStatusChecker = new ResponseStatusChecker([]);
        var headersFactory = new HeadersFactory([]);
        var resiliencePipelineFactory = new ResiliencePipelineFactory(options.RetryOptions);
        _rawClient =
            new RawClient(httpClient, urlFactory, responseStatusChecker, headersFactory, resiliencePipelineFactory);
        _httpBearerScheme = token != null ? new HttpBearerScheme(token) : NoneAuthScheme.Instance;
    }

    public Task<AccountGetresponse1> GetAccount(string accountId,
        string? xFapiAuthDate,
        string? xFapiCustomerIpAddress,
        string? xFapiInteractionId,
        string? xMerchantIpAddress,
        string? xCustomerUserAgent,
        CancellationToken cancellationToken = default) =>
        _rawClient.Execute("/accounts/{AccountId}",
            [new TemplateParam("AccountId", accountId)],
            [],
            [new HeaderParam("x-fapi-auth-date", xFapiAuthDate),
                new HeaderParam("x-fapi-customer-ip-address", xFapiCustomerIpAddress),
                new HeaderParam("x-fapi-interaction-id", xFapiInteractionId),
                new HeaderParam("x-merchant-ip-address", xMerchantIpAddress),
                new HeaderParam("x-customer-user-agent", xCustomerUserAgent)],
            HttpMethod.Get,
            EmptyBody.Instance,
            JsonResponse.Create<AccountGetresponse1>(),
            VoidErrorResponse.Instance,
            [_httpBearerScheme],
            cancellationToken);

    public Task<AccountGetresponse> GetAccounts(string? xFapiAuthDate,
        string? xFapiCustomerIpAddress,
        string? xFapiInteractionId,
        string? xMerchantIpAddress,
        string? xCustomerUserAgent,
        CancellationToken cancellationToken = default) =>
        _rawClient.Execute("/accounts",
            [],
            [],
            [new HeaderParam("x-fapi-auth-date", xFapiAuthDate),
                new HeaderParam("x-fapi-customer-ip-address", xFapiCustomerIpAddress),
                new HeaderParam("x-fapi-interaction-id", xFapiInteractionId),
                new HeaderParam("x-merchant-ip-address", xMerchantIpAddress),
                new HeaderParam("x-customer-user-agent", xCustomerUserAgent)],
            HttpMethod.Get,
            EmptyBody.Instance,
            JsonResponse.Create<AccountGetresponse>(),
            VoidErrorResponse.Instance,
            [_httpBearerScheme],
            cancellationToken);

    public Task<BalancesGetresponse> GetBalances(string? xFapiAuthDate,
        string? xFapiCustomerIpAddress,
        string? xFapiInteractionId,
        string? xMerchantIpAddress,
        string? xCustomerUserAgent,
        CancellationToken cancellationToken = default) =>
        _rawClient.Execute("/balances",
            [],
            [],
            [new HeaderParam("x-fapi-auth-date", xFapiAuthDate),
                new HeaderParam("x-fapi-customer-ip-address", xFapiCustomerIpAddress),
                new HeaderParam("x-fapi-interaction-id", xFapiInteractionId),
                new HeaderParam("x-merchant-ip-address", xMerchantIpAddress),
                new HeaderParam("x-customer-user-agent", xCustomerUserAgent)],
            HttpMethod.Get,
            EmptyBody.Instance,
            JsonResponse.Create<BalancesGetresponse>(),
            VoidErrorResponse.Instance,
            [_httpBearerScheme],
            cancellationToken);

    public Task<BalancesGetresponse> GetAccountBalances(string accountId,
        string? xFapiAuthDate,
        string? xFapiCustomerIpAddress,
        string? xFapiInteractionId,
        string? xMerchantIpAddress,
        string? xCustomerUserAgent,
        CancellationToken cancellationToken = default) =>
        _rawClient.Execute("/accounts/{AccountId}/balances",
            [new TemplateParam("AccountId", accountId)],
            [],
            [new HeaderParam("x-fapi-auth-date", xFapiAuthDate),
                new HeaderParam("x-fapi-customer-ip-address", xFapiCustomerIpAddress),
                new HeaderParam("x-fapi-interaction-id", xFapiInteractionId),
                new HeaderParam("x-merchant-ip-address", xMerchantIpAddress),
                new HeaderParam("x-customer-user-agent", xCustomerUserAgent)],
            HttpMethod.Get,
            EmptyBody.Instance,
            JsonResponse.Create<BalancesGetresponse>(),
            VoidErrorResponse.Instance,
            [_httpBearerScheme],
            cancellationToken);

    public Task<BeneficiariesGetresponse> GetAccountBeneficiaries(string accountId,
        string? xFapiAuthDate,
        string? xFapiCustomerIpAddress,
        string? xFapiInteractionId,
        string? xMerchantIpAddress,
        string? xCustomerUserAgent,
        CancellationToken cancellationToken = default) =>
        _rawClient.Execute("/accounts/{AccountId}/beneficiaries",
            [new TemplateParam("AccountId", accountId)],
            [],
            [new HeaderParam("x-fapi-auth-date", xFapiAuthDate),
                new HeaderParam("x-fapi-customer-ip-address", xFapiCustomerIpAddress),
                new HeaderParam("x-fapi-interaction-id", xFapiInteractionId),
                new HeaderParam("x-merchant-ip-address", xMerchantIpAddress),
                new HeaderParam("x-customer-user-agent", xCustomerUserAgent)],
            HttpMethod.Get,
            EmptyBody.Instance,
            JsonResponse.Create<BeneficiariesGetresponse>(),
            VoidErrorResponse.Instance,
            [_httpBearerScheme],
            cancellationToken);

    public Task<BeneficiariesGetresponse> GetBeneficiaries(string? xFapiAuthDate,
        string? xFapiCustomerIpAddress,
        string? xFapiInteractionId,
        string? xMerchantIpAddress,
        string? xCustomerUserAgent,
        CancellationToken cancellationToken = default) =>
        _rawClient.Execute("/beneficiaries",
            [],
            [],
            [new HeaderParam("x-fapi-auth-date", xFapiAuthDate),
                new HeaderParam("x-fapi-customer-ip-address", xFapiCustomerIpAddress),
                new HeaderParam("x-fapi-interaction-id", xFapiInteractionId),
                new HeaderParam("x-merchant-ip-address", xMerchantIpAddress),
                new HeaderParam("x-customer-user-agent", xCustomerUserAgent)],
            HttpMethod.Get,
            EmptyBody.Instance,
            JsonResponse.Create<BeneficiariesGetresponse>(),
            VoidErrorResponse.Instance,
            [_httpBearerScheme],
            cancellationToken);

    public Task<DirectDebitGetresponse> GetAccountDirectDebits(string accountId,
        string? xFapiAuthDate,
        string? xFapiCustomerIpAddress,
        string? xFapiInteractionId,
        string? xMerchantIpAddress,
        string? xCustomerUserAgent,
        CancellationToken cancellationToken = default) =>
        _rawClient.Execute("/accounts/{AccountId}/direct-debits",
            [new TemplateParam("AccountId", accountId)],
            [],
            [new HeaderParam("x-fapi-auth-date", xFapiAuthDate),
                new HeaderParam("x-fapi-customer-ip-address", xFapiCustomerIpAddress),
                new HeaderParam("x-fapi-interaction-id", xFapiInteractionId),
                new HeaderParam("x-merchant-ip-address", xMerchantIpAddress),
                new HeaderParam("x-customer-user-agent", xCustomerUserAgent)],
            HttpMethod.Get,
            EmptyBody.Instance,
            JsonResponse.Create<DirectDebitGetresponse>(),
            VoidErrorResponse.Instance,
            [_httpBearerScheme],
            cancellationToken);

    public Task<DirectDebitGetresponse> GetDirectDebits(string? xFapiAuthDate,
        string? xFapiCustomerIpAddress,
        string? xFapiInteractionId,
        string? xMerchantIpAddress,
        string? xCustomerUserAgent,
        CancellationToken cancellationToken = default) =>
        _rawClient.Execute("/direct-debits",
            [],
            [],
            [new HeaderParam("x-fapi-auth-date", xFapiAuthDate),
                new HeaderParam("x-fapi-customer-ip-address", xFapiCustomerIpAddress),
                new HeaderParam("x-fapi-interaction-id", xFapiInteractionId),
                new HeaderParam("x-merchant-ip-address", xMerchantIpAddress),
                new HeaderParam("x-customer-user-agent", xCustomerUserAgent)],
            HttpMethod.Get,
            EmptyBody.Instance,
            JsonResponse.Create<DirectDebitGetresponse>(),
            VoidErrorResponse.Instance,
            [_httpBearerScheme],
            cancellationToken);

    public Task<GetAccountOffersResponse> GetAccountOffers(string accountId,
        string? xFapiAuthDate,
        string? xFapiCustomerIpAddress,
        string? xFapiInteractionId,
        string? xMerchantIpAddress,
        string? xCustomerUserAgent,
        CancellationToken cancellationToken = default) =>
        _rawClient.Execute("/accounts/{AccountId}/offers",
            [new TemplateParam("AccountId", accountId)],
            [],
            [new HeaderParam("x-fapi-auth-date", xFapiAuthDate),
                new HeaderParam("x-fapi-customer-ip-address", xFapiCustomerIpAddress),
                new HeaderParam("x-fapi-interaction-id", xFapiInteractionId),
                new HeaderParam("x-merchant-ip-address", xMerchantIpAddress),
                new HeaderParam("x-customer-user-agent", xCustomerUserAgent)],
            HttpMethod.Get,
            EmptyBody.Instance,
            JsonResponse.Create<GetAccountOffersResponse>(),
            VoidErrorResponse.Instance,
            [_httpBearerScheme],
            cancellationToken);

    public Task<GetOffersResponse> GetOffers(string? xFapiAuthDate,
        string? xFapiCustomerIpAddress,
        string? xFapiInteractionId,
        string? xMerchantIpAddress,
        string? xCustomerUserAgent,
        CancellationToken cancellationToken = default) =>
        _rawClient.Execute("/offers",
            [],
            [],
            [new HeaderParam("x-fapi-auth-date", xFapiAuthDate),
                new HeaderParam("x-fapi-customer-ip-address", xFapiCustomerIpAddress),
                new HeaderParam("x-fapi-interaction-id", xFapiInteractionId),
                new HeaderParam("x-merchant-ip-address", xMerchantIpAddress),
                new HeaderParam("x-customer-user-agent", xCustomerUserAgent)],
            HttpMethod.Get,
            EmptyBody.Instance,
            JsonResponse.Create<GetOffersResponse>(),
            VoidErrorResponse.Instance,
            [_httpBearerScheme],
            cancellationToken);

    public Task<GetAccountPartyResponse> GetAccountParty(string accountId,
        string? xFapiAuthDate,
        string? xFapiCustomerIpAddress,
        string? xFapiInteractionId,
        string? xMerchantIpAddress,
        string? xCustomerUserAgent,
        CancellationToken cancellationToken = default) =>
        _rawClient.Execute("/accounts/{AccountId}/party",
            [new TemplateParam("AccountId", accountId)],
            [],
            [new HeaderParam("x-fapi-auth-date", xFapiAuthDate),
                new HeaderParam("x-fapi-customer-ip-address", xFapiCustomerIpAddress),
                new HeaderParam("x-fapi-interaction-id", xFapiInteractionId),
                new HeaderParam("x-merchant-ip-address", xMerchantIpAddress),
                new HeaderParam("x-customer-user-agent", xCustomerUserAgent)],
            HttpMethod.Get,
            EmptyBody.Instance,
            JsonResponse.Create<GetAccountPartyResponse>(),
            VoidErrorResponse.Instance,
            [_httpBearerScheme],
            cancellationToken);

    public Task<GetPartyResponse> GetParty(string? xFapiAuthDate,
        string? xFapiCustomerIpAddress,
        string? xFapiInteractionId,
        string? xMerchantIpAddress,
        string? xCustomerUserAgent,
        CancellationToken cancellationToken = default) =>
        _rawClient.Execute("/party",
            [],
            [],
            [new HeaderParam("x-fapi-auth-date", xFapiAuthDate),
                new HeaderParam("x-fapi-customer-ip-address", xFapiCustomerIpAddress),
                new HeaderParam("x-fapi-interaction-id", xFapiInteractionId),
                new HeaderParam("x-merchant-ip-address", xMerchantIpAddress),
                new HeaderParam("x-customer-user-agent", xCustomerUserAgent)],
            HttpMethod.Get,
            EmptyBody.Instance,
            JsonResponse.Create<GetPartyResponse>(),
            VoidErrorResponse.Instance,
            [_httpBearerScheme],
            cancellationToken);

    public Task<GetAccountScheduledPaymentsResponse> GetAccountScheduledPayments(string accountId,
        string? xFapiAuthDate,
        string? xFapiCustomerIpAddress,
        string? xFapiInteractionId,
        string? xMerchantIpAddress,
        string? xCustomerUserAgent,
        CancellationToken cancellationToken = default) =>
        _rawClient.Execute("/accounts/{AccountId}/scheduled-payments",
            [new TemplateParam("AccountId", accountId)],
            [],
            [new HeaderParam("x-fapi-auth-date", xFapiAuthDate),
                new HeaderParam("x-fapi-customer-ip-address", xFapiCustomerIpAddress),
                new HeaderParam("x-fapi-interaction-id", xFapiInteractionId),
                new HeaderParam("x-merchant-ip-address", xMerchantIpAddress),
                new HeaderParam("x-customer-user-agent", xCustomerUserAgent)],
            HttpMethod.Get,
            EmptyBody.Instance,
            JsonResponse.Create<GetAccountScheduledPaymentsResponse>(),
            VoidErrorResponse.Instance,
            [_httpBearerScheme],
            cancellationToken);

    public Task<GetScheduledPaymentsResponse> GetScheduledPayments(string? xFapiAuthDate,
        string? xFapiCustomerIpAddress,
        string? xFapiInteractionId,
        string? xMerchantIpAddress,
        string? xCustomerUserAgent,
        CancellationToken cancellationToken = default) =>
        _rawClient.Execute("/scheduled-payments",
            [],
            [],
            [new HeaderParam("x-fapi-auth-date", xFapiAuthDate),
                new HeaderParam("x-fapi-customer-ip-address", xFapiCustomerIpAddress),
                new HeaderParam("x-fapi-interaction-id", xFapiInteractionId),
                new HeaderParam("x-merchant-ip-address", xMerchantIpAddress),
                new HeaderParam("x-customer-user-agent", xCustomerUserAgent)],
            HttpMethod.Get,
            EmptyBody.Instance,
            JsonResponse.Create<GetScheduledPaymentsResponse>(),
            VoidErrorResponse.Instance,
            [_httpBearerScheme],
            cancellationToken);

    public Task<StandingOrdersGetresponse> GetAccountStandingOrders(string accountId,
        string? xFapiAuthDate,
        string? xFapiCustomerIpAddress,
        string? xFapiInteractionId,
        string? xMerchantIpAddress,
        string? xCustomerUserAgent,
        CancellationToken cancellationToken = default) =>
        _rawClient.Execute("/accounts/{AccountId}/standing-orders",
            [new TemplateParam("AccountId", accountId)],
            [],
            [new HeaderParam("x-fapi-auth-date", xFapiAuthDate),
                new HeaderParam("x-fapi-customer-ip-address", xFapiCustomerIpAddress),
                new HeaderParam("x-fapi-interaction-id", xFapiInteractionId),
                new HeaderParam("x-merchant-ip-address", xMerchantIpAddress),
                new HeaderParam("x-customer-user-agent", xCustomerUserAgent)],
            HttpMethod.Get,
            EmptyBody.Instance,
            JsonResponse.Create<StandingOrdersGetresponse>(),
            VoidErrorResponse.Instance,
            [_httpBearerScheme],
            cancellationToken);

    public Task<StandingOrdersGetresponse> GetStandingOrders(string? xFapiAuthDate,
        string? xFapiCustomerIpAddress,
        string? xFapiInteractionId,
        string? xMerchantIpAddress,
        string? xCustomerUserAgent,
        CancellationToken cancellationToken = default) =>
        _rawClient.Execute("/standing-orders",
            [],
            [],
            [new HeaderParam("x-fapi-auth-date", xFapiAuthDate),
                new HeaderParam("x-fapi-customer-ip-address", xFapiCustomerIpAddress),
                new HeaderParam("x-fapi-interaction-id", xFapiInteractionId),
                new HeaderParam("x-merchant-ip-address", xMerchantIpAddress),
                new HeaderParam("x-customer-user-agent", xCustomerUserAgent)],
            HttpMethod.Get,
            EmptyBody.Instance,
            JsonResponse.Create<StandingOrdersGetresponse>(),
            VoidErrorResponse.Instance,
            [_httpBearerScheme],
            cancellationToken);

    public Task<GetAccountStatementResponse> GetAccountStatement(string accountId,
        string statementId,
        DateTimeOffset? fromStatementDateTime,
        DateTimeOffset? toStatementDateTime,
        string? xFapiAuthDate,
        string? xFapiCustomerIpAddress,
        string? xFapiInteractionId,
        string? xMerchantIpAddress,
        string? xCustomerUserAgent,
        CancellationToken cancellationToken = default) =>
        _rawClient.Execute("/accounts/{AccountId}/statements/{StatementId}",
            [new TemplateParam("AccountId", accountId), new TemplateParam("StatementId", statementId)],
            [new Param("fromStatementDateTime", fromStatementDateTime),
                new Param("toStatementDateTime", toStatementDateTime)],
            [new HeaderParam("x-fapi-auth-date", xFapiAuthDate),
                new HeaderParam("x-fapi-customer-ip-address", xFapiCustomerIpAddress),
                new HeaderParam("x-fapi-interaction-id", xFapiInteractionId),
                new HeaderParam("x-merchant-ip-address", xMerchantIpAddress),
                new HeaderParam("x-customer-user-agent", xCustomerUserAgent)],
            HttpMethod.Get,
            EmptyBody.Instance,
            JsonResponse.Create<GetAccountStatementResponse>(),
            VoidErrorResponse.Instance,
            [_httpBearerScheme],
            cancellationToken);

    public Task GetAccountStatementFile(string accountId,
        string statementId,
        string? xFapiAuthDate,
        string? xFapiCustomerIpAddress,
        string? xFapiInteractionId,
        string? xMerchantIpAddress,
        string? xCustomerUserAgent,
        CancellationToken cancellationToken = default) =>
        _rawClient.Execute("/accounts/{AccountId}/statements/{StatementId}/file",
            [new TemplateParam("AccountId", accountId), new TemplateParam("StatementId", statementId)],
            [],
            [new HeaderParam("x-fapi-auth-date", xFapiAuthDate),
                new HeaderParam("x-fapi-customer-ip-address", xFapiCustomerIpAddress),
                new HeaderParam("x-fapi-interaction-id", xFapiInteractionId),
                new HeaderParam("x-merchant-ip-address", xMerchantIpAddress),
                new HeaderParam("x-customer-user-agent", xCustomerUserAgent)],
            HttpMethod.Get,
            EmptyBody.Instance,
            VoidResponse.Instance,
            VoidErrorResponse.Instance,
            [_httpBearerScheme],
            cancellationToken);

    public Task<GetAccountStatementTransactionsResponse> GetAccountStatementTransactions(string accountId,
        string statementId,
        DateTimeOffset? fromBookingDateTime,
        DateTimeOffset? toBookingDateTime,
        string? xFapiAuthDate,
        string? xFapiCustomerIpAddress,
        string? xFapiInteractionId,
        string? xMerchantIpAddress,
        string? xCustomerUserAgent,
        CancellationToken cancellationToken = default) =>
        _rawClient.Execute("/accounts/{AccountId}/statements/{StatementId}/transactions",
            [new TemplateParam("AccountId", accountId), new TemplateParam("StatementId", statementId)],
            [new Param("fromBookingDateTime", fromBookingDateTime), new Param("toBookingDateTime", toBookingDateTime)],
            [new HeaderParam("x-fapi-auth-date", xFapiAuthDate),
                new HeaderParam("x-fapi-customer-ip-address", xFapiCustomerIpAddress),
                new HeaderParam("x-fapi-interaction-id", xFapiInteractionId),
                new HeaderParam("x-merchant-ip-address", xMerchantIpAddress),
                new HeaderParam("x-customer-user-agent", xCustomerUserAgent)],
            HttpMethod.Get,
            EmptyBody.Instance,
            JsonResponse.Create<GetAccountStatementTransactionsResponse>(),
            VoidErrorResponse.Instance,
            [_httpBearerScheme],
            cancellationToken);

    public Task<GetAccountStatementsResponse> GetAccountStatements(string accountId,
        DateTimeOffset? fromStatementDateTime,
        DateTimeOffset? toStatementDateTime,
        string? xFapiAuthDate,
        string? xFapiCustomerIpAddress,
        string? xFapiInteractionId,
        string? xMerchantIpAddress,
        string? xCustomerUserAgent,
        CancellationToken cancellationToken = default) =>
        _rawClient.Execute("/accounts/{AccountId}/statements",
            [new TemplateParam("AccountId", accountId)],
            [new Param("fromStatementDateTime", fromStatementDateTime),
                new Param("toStatementDateTime", toStatementDateTime)],
            [new HeaderParam("x-fapi-auth-date", xFapiAuthDate),
                new HeaderParam("x-fapi-customer-ip-address", xFapiCustomerIpAddress),
                new HeaderParam("x-fapi-interaction-id", xFapiInteractionId),
                new HeaderParam("x-merchant-ip-address", xMerchantIpAddress),
                new HeaderParam("x-customer-user-agent", xCustomerUserAgent)],
            HttpMethod.Get,
            EmptyBody.Instance,
            JsonResponse.Create<GetAccountStatementsResponse>(),
            VoidErrorResponse.Instance,
            [_httpBearerScheme],
            cancellationToken);

    public Task<GetStatementsResponse> GetStatements(DateTimeOffset? fromStatementDateTime,
        DateTimeOffset? toStatementDateTime,
        string? xFapiAuthDate,
        string? xFapiCustomerIpAddress,
        string? xFapiInteractionId,
        string? xMerchantIpAddress,
        string? xCustomerUserAgent,
        CancellationToken cancellationToken = default) =>
        _rawClient.Execute("/statements",
            [],
            [new Param("fromStatementDateTime", fromStatementDateTime),
                new Param("toStatementDateTime", toStatementDateTime)],
            [new HeaderParam("x-fapi-auth-date", xFapiAuthDate),
                new HeaderParam("x-fapi-customer-ip-address", xFapiCustomerIpAddress),
                new HeaderParam("x-fapi-interaction-id", xFapiInteractionId),
                new HeaderParam("x-merchant-ip-address", xMerchantIpAddress),
                new HeaderParam("x-customer-user-agent", xCustomerUserAgent)],
            HttpMethod.Get,
            EmptyBody.Instance,
            JsonResponse.Create<GetStatementsResponse>(),
            VoidErrorResponse.Instance,
            [_httpBearerScheme],
            cancellationToken);

    public Task<TransactionsGetresponse> GetAccountTransactions(string accountId,
        DateTimeOffset? fromBookingDateTime,
        DateTimeOffset? toBookingDateTime,
        string? xFapiAuthDate,
        string? xFapiCustomerIpAddress,
        string? xFapiInteractionId,
        string? xMerchantIpAddress,
        string? xCustomerUserAgent,
        CancellationToken cancellationToken = default) =>
        _rawClient.Execute("/accounts/{AccountId}/transactions",
            [new TemplateParam("AccountId", accountId)],
            [new Param("fromBookingDateTime", fromBookingDateTime), new Param("toBookingDateTime", toBookingDateTime)],
            [new HeaderParam("x-fapi-auth-date", xFapiAuthDate),
                new HeaderParam("x-fapi-customer-ip-address", xFapiCustomerIpAddress),
                new HeaderParam("x-fapi-interaction-id", xFapiInteractionId),
                new HeaderParam("x-merchant-ip-address", xMerchantIpAddress),
                new HeaderParam("x-customer-user-agent", xCustomerUserAgent)],
            HttpMethod.Get,
            EmptyBody.Instance,
            JsonResponse.Create<TransactionsGetresponse>(),
            VoidErrorResponse.Instance,
            [_httpBearerScheme],
            cancellationToken);

    public Task<TransactionsGetresponse> GetTransactions(DateTimeOffset? fromBookingDateTime,
        DateTimeOffset? toBookingDateTime,
        string? xFapiAuthDate,
        string? xFapiCustomerIpAddress,
        string? xFapiInteractionId,
        string? xMerchantIpAddress,
        string? xCustomerUserAgent,
        CancellationToken cancellationToken = default) =>
        _rawClient.Execute("/transactions",
            [],
            [new Param("fromBookingDateTime", fromBookingDateTime), new Param("toBookingDateTime", toBookingDateTime)],
            [new HeaderParam("x-fapi-auth-date", xFapiAuthDate),
                new HeaderParam("x-fapi-customer-ip-address", xFapiCustomerIpAddress),
                new HeaderParam("x-fapi-interaction-id", xFapiInteractionId),
                new HeaderParam("x-merchant-ip-address", xMerchantIpAddress),
                new HeaderParam("x-customer-user-agent", xCustomerUserAgent)],
            HttpMethod.Get,
            EmptyBody.Instance,
            JsonResponse.Create<TransactionsGetresponse>(),
            VoidErrorResponse.Instance,
            [_httpBearerScheme],
            cancellationToken);
}
